"""External-load and exposure scientific identity and deterministic operations."""

from dynamislm.external_load.comparability import (
    ExternalLoadComparabilityRequest,
    assess_external_load_comparability,
    assess_external_load_measurement_comparability,
    compare_external_load_identities,
    compare_external_load_measurement_identities,
    compare_external_load_observations,
)
from dynamislm.external_load.identity import (
    AggregationContext,
    AggregationIdentity,
    AggregationScope,
    EventDefinition,
    EventHysteresisIdentity,
    EventHysteresisStatus,
    ExternalLoadAggregationIdentity,
    ExternalLoadAggregationWindow,
    ExternalLoadDefinitionStatus,
    ExternalLoadEventDefinition,
    ExternalLoadIdentity,
    ExternalLoadMeasurementIdentity,
    ExternalLoadMetricFamily,
    ExternalLoadMetricKind,
    ExternalLoadModality,
    ExternalLoadNormalizationIdentity,
    ExternalLoadProcessingIdentity,
    ExternalLoadSystemIdentity,
    ExternalLoadThresholdIdentity,
    ExternalLoadValueOrigin,
    NormalizationIdentity,
    NormalizationKind,
    ProcessingComponentStatus,
    ProcessingStepIdentity,
    ThresholdBasis,
    ThresholdBoundary,
    ThresholdIdentity,
)
from dynamislm.external_load.mapping import (
    SOURCE_A_MAPPING_VERSION,
    ExternalLoadSourceMapping,
    build_external_load_observation,
    build_provider_derived_observation,
    map_source_a_record,
    map_source_a_records,
    map_source_a_variable,
    source_a_external_column_names,
    source_a_mapping_for_record,
    source_a_mapping_for_variable,
)
from dynamislm.external_load.metrics import (
    ExternalLoadComputationError,
    ExternalLoadComputationStatus,
    ExternalLoadMetricResult,
    ExternalLoadThresholdSummary,
    ExternalLoadVelocitySeriesEvidence,
    VelocitySample,
    VelocitySeries,
    calculate_relative_distance,
    calculate_velocity_threshold_summary,
    convert_external_load_value,
    derive_duration_normalized_distance,
    duration_normalized_distance,
    normalize_external_load_unit,
    refuse_unregistered_external_load_computation,
    relative_distance,
    summarize_velocity_threshold,
    threshold_summary_from_velocity_series,
)
from dynamislm.external_load.registry import *  # noqa: F403

__all__ = [
    "SOURCE_A_MAPPING_VERSION",
    "AggregationContext",
    "AggregationIdentity",
    "AggregationScope",
    "EventDefinition",
    "EventHysteresisIdentity",
    "EventHysteresisStatus",
    "ExternalLoadAggregationIdentity",
    "ExternalLoadAggregationWindow",
    "ExternalLoadComparabilityRequest",
    "ExternalLoadComputationError",
    "ExternalLoadComputationStatus",
    "ExternalLoadDefinitionStatus",
    "ExternalLoadEventDefinition",
    "ExternalLoadIdentity",
    "ExternalLoadMeasurementIdentity",
    "ExternalLoadMetricFamily",
    "ExternalLoadMetricKind",
    "ExternalLoadMetricResult",
    "ExternalLoadModality",
    "ExternalLoadNormalizationIdentity",
    "ExternalLoadProcessingIdentity",
    "ExternalLoadSourceMapping",
    "ExternalLoadSystemIdentity",
    "ExternalLoadThresholdIdentity",
    "ExternalLoadThresholdSummary",
    "ExternalLoadValueOrigin",
    "ExternalLoadVelocitySeriesEvidence",
    "NormalizationIdentity",
    "NormalizationKind",
    "ProcessingComponentStatus",
    "ProcessingStepIdentity",
    "ThresholdBasis",
    "ThresholdBoundary",
    "ThresholdIdentity",
    "VelocitySample",
    "VelocitySeries",
    "assess_external_load_comparability",
    "assess_external_load_measurement_comparability",
    "build_external_load_observation",
    "build_provider_derived_observation",
    "calculate_relative_distance",
    "calculate_velocity_threshold_summary",
    "compare_external_load_identities",
    "compare_external_load_measurement_identities",
    "compare_external_load_observations",
    "convert_external_load_value",
    "derive_duration_normalized_distance",
    "duration_normalized_distance",
    "map_source_a_record",
    "map_source_a_records",
    "map_source_a_variable",
    "normalize_external_load_unit",
    "refuse_unregistered_external_load_computation",
    "relative_distance",
    "source_a_external_column_names",
    "source_a_mapping_for_record",
    "source_a_mapping_for_variable",
    "summarize_velocity_threshold",
    "threshold_summary_from_velocity_series",
]
# Include the intentional registry surface without restating every reference
# in this module's import list.
from dynamislm.external_load import registry as _registry

__all__ += list(_registry.__all__)
